---
- name: 'run the certbot container'
  community.docker.docker_container:
    name: 'certbot-namesilo'
    image: 'certbot-namesilo'
    auto_remove: true
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
    env:
      CERTBOT_EMAIL: '{{ certbot_email }}'
      CERTBOT_NAMESILO_API_KEY: '{{ certbot_namesilo_apikey }}'
...
