---
- name: "Read Log for renewals"
  ansible.builtin.slurp:
    src: "/etc/letsencrypt/certbot_run.log"
  register: "certbot_run_log"
  tags:
    - "certbot:post-run"

- name: "Set log as list"
  ansible.builtin.set_fact:
    log_list: "{{ cerbot_run_log['content'] | b64decode | split('\n') }}"
  tags:
    - "certbot:post-run"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ log_list }}"
  tags:
    - "certbot:post-run"
...
